/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	valores  soma_1_arg;
	
	printf("Digite o valor 1: ");
	scanf("%i",&soma_1_arg.v1);
	
	printf("\nDigite o valor 2: ");
	scanf("%i",&soma_1_arg.v2);
	
	

#ifndef	DEBUG
	clnt = clnt_create (host, calc, calc1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = soma_1(&soma_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	
	printf("\nResultado %i \n",*result_1);
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char host[16];

	printf("Digite o ip: ");
	scanf("%s",host);

	


	calc_1 (host);
exit (0);
}
