/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_valores (XDR *xdrs, valores *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->v1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->v2))
		 return FALSE;
	return TRUE;
}
