/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct valores {
	int v1;
	int v2;
};
typedef struct valores valores;

#define calc 300000001
#define calc1 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  int * soma_1(valores *, CLIENT *);
extern  int * soma_1_svc(valores *, struct svc_req *);
extern int calc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  int * soma_1();
extern  int * soma_1_svc();
extern int calc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_valores (XDR *, valores*);

#else /* K&R C */
extern bool_t xdr_valores ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
